### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by searsia** [searsia/searsiaserver#10]
Add support for the server to run securely using https.

**Comment by almer-t** [comment]
This probably is not technically challenging to implement, but providing proper certificates can be a bit of a pain. Modern browsers (rightly) warn you when accessing sites with unverifiable certificates. My suggestion is to look into https://letsencrypt.org/ for hosted solutions (e.g. that require a domain name, certificates are issued free of costs), and for testing rely on self-signed local certificates.

**Comment by searsia** [comment]
We no longer plan to add https support to searsiaserver directly. Instead, use your web server's configuration to forward https request to searsiaserver. An example configuration for Nginx using Let's Encrypt can be found in ths following gist: [yourdomain](https://gist.github.com/searsia/a79954118869ae77bb5ee588ef4a685c).
