### ISSUE TITLE
proxy-mode

### ISSUE THREAD

**Issue by searsia** [searsia/searsiaserver#11]
Add a proxy-mode, that fetches everything, images, clicks, etc. via the server. This way, the end user cannot be tracked by the individual search engines.
See also the post on clicks at Duckduckgo: https://duck.co/help/results/rduckduckgocom

**Comment by almer-t** [comment]
This is an excellent idea, the downside though is that it puts heavy strain on the server, as it will have to fetch all resources for all clients. This can be alleviated by some sort of caching mechanism to some extent. Another option is to add a Tor proxy configuration option to the client, through which all such resources are downloaded. This eliminates server strain, and effectively anonymizes all out of band requests.

**Comment by searsia** [comment]
A simple (undocumented) implementation (that indeed puts a strain on the server) is now available in the client, as follows. Add a URL template to the variable proxyURL:

    var proxyURL = 'https://yourdomain.top/proxy.php?url={u}'

The proxy is only used to fetch remote images. An example implementation that fetches only images smaller than 500 kb can be found at: [proxy.php](https://gist.github.com/searsia/e141c4aca4ca1f3bd8a2c04877f4b26e)
This implementation reliefs some strain on the server by responding with "HTTP 304 Not Modified" if the client already has the image.

**Comment by searsia** [comment]
There is no solution for clicks, although, search term leakage via clicks is prevented by the referrer policy ‘no-referrer’ in the client.
