### ISSUE TITLE
Can't add resource. DomException: INVALID_CHARACTER_ERR

### ISSUE THREAD

**Issue by WimVanDerZijden** [searsia/searsiaserver#5]
I'm trying to add the following resource.

api template: http://www.pokercity.nl/search-news.aspx?q={q}
xpath item: `//div[@class='newslister']`
title: `.//h2`
url: `.//h2/../@href`

This gives the following error in the client:

> Update failed.
> 503 Service Unavailable.
> Resource unavailable: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 

Some other questions I have:

- Is queries.log the only logging file we have or are there more? I can't find any logging information when the above exception occurs, even when running with --log 4.

- Is there a way to disable resources?

- How do you prevent the server from cloning search.utwente.nl?

**Comment by djoerd** [comment]
Looks like an XML error. Just checking: What is the mimetype of this resource? Try: "text/html". About the other questions:
* Logging is only partly implemented. If the queries.log file doesn't list anything, I am afraid that you're on your own on this one.
* Disabling resources can be done in the client by the 'delete' button.
* If you start the server with the option `--mother=none` you start with a fresh server.

**Comment by WimVanDerZijden** [comment]
I did specify text/html.
I would like to debug this myself but I have a hard time locating the position in code where this error would occur. Can you point me in the right direction?

**Comment by djoerd** [comment]
Wow, thanks. What happens is the following:
    org.searsia.engine.SearchException: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
    at org.searsia.engine.SearchEngine.createPrivateSearchException(SearchEngine.java:387)
    at org.searsia.engine.SearchEngine.search(SearchEngine.java:251)

Which I think originates from:
    DOMBuilder.jsoup2DOM()
which translates a jsoup object to an XML DOM (to be used for the XPath queries later on)

That is, Line 251 contains an ugly catch all Exception, that seems to originate from Line 244:
    result = xpathSearch(url, page, debug);
which seems to originate from Line 318:
    document = parseDocumentHTML(page, url);

**Comment by djoerd** [comment]
Here's a hypothesis: The system uses the wrong charset (see e.g. https://sourceforge.net/p/htmlcleaner/discussion/637246/thread/2fe3cf56/). The website you were testing uses charset=iso-8859-1. If that is the problem, it should be solved in Line 413 and further in org.searsia.engine.SearchEngine in getCompleteWebPage()...

**Comment by djoerd** [comment]
Fixed in the master branch (version 0.3.2) by catching the DOMException.

**Comment by WimVanDerZijden** [comment]
Thanks that's great. On a side note, is there an easy way to import the project into Eclipse? The method I used for this is somewhat involved. I imported it as a general project, then used Project Properties -> Project Facets to convert it to a Java project, then ran the pom.xml as Maven build 'clean install', then added target/searsiaserver.jar to the Java build path.

**Comment by djoerd** [comment]
A wise person once said, you can make me use Eclipse, but you can't make me like it (https://twitter.com/gvanrossum/status/424595747397332992).

For me this works:

    mvn clean package eclipse:eclipse

And then in Eclipse: -> Import -> Existing project into workspace

**Comment by WimVanDerZijden** [comment]
Thanks, that fixed the problem.
