### ISSUE TITLE
DOMException: invalid character error

### ISSUE THREAD

**Issue by iisys-** [searsia/searsiaserver#8]
Hello!

With some resources, I get the following error:
```
Update failed.
503 Service Unavailable.
Resource unavailable: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
```

You can reproduce this by adding (for example) `http://www.imdb.com/find?q={q}`.
IMDb is just an example; I got the error with a few more resources. Perhaps it has something to do with the encoding? The XPath strings don't matter: I set that to `//html` to make sure the error doesn't come from that part.

Am I doing something wrong or is this a genuine bug?

**Comment by djoerd** [comment]
Yes, that seems to be a genuine bug: I believe this bug was is described in Issue #5.
It is solved in version 0.3.2, which is the current master on github (but not yet released: you have to clone and compile yourself).
