### ISSUE TITLE
Unable to work with two instances

### ISSUE THREAD

**Issue by iisys-** [searsia/searsiaserver#9]
Hi!

We're trying to run two instances of the (0.4.0) server for testing purposes. Hoewever, we can't get the second server to work properly.

The problem seems to be with the server-side storage of the resource on the second instance. We can start the actual second instance and add a resource, but when we request the resource information from the second server instance, it says the resource identifier is unknown.

We tried it with both Eclipse and stand-alone jars. We started the instances with different server names and different ports, so there are no index or port conflicts. Furthermore, we started both instances with the --open argument. The update on the client-side works (the "Update" button), but the resource doesn't get saved on the server side. Oh, and we used two different clients to handle the different server instances, of course.

Any suggestions? And is this a bug?

**Comment by djoerd** [comment]
Not sure whether it is a bug in the server. Can you give the two exact commands (i.e. all parameters) used for both instances? 

Another problem might be the clients. They use the browser localStorage, and if both servers are on localhost (or the same domain), I guess all resources are getting mixed up.

**Comment by iisys-** [comment]
These are the arguments used:
```
--name iilt1 --log 4 --open --url http://localhost:16842/searsia/ --mother none
--name iilt2 --log 4 --open --url http://localhost:16843/searsia/ --mother none
```
We tried variations. The --mother arguments is passed so no unnecessary resources are retrieved from search.utwente.nl. The log doesn't have any meaningful entries. Changing the path doesn't do much, because all files and directories in that path are prefixed with the server name.

The same goes for the localStorage in the clients: all relevant entries are prefixed with the server name, so no conflicts arise.

**Comment by djoerd** [comment]
Seems like the right thing to do. I have no clue: Maybe the resource was not added properly after all?

We've run multiple instances on one machine before, so that should be no problem. One difference: This was done with v0.3.2, maybe you can do a quick check and see if you can replicate the same problem with that version v0.3.2? Let me know if that fails too. This is also the version that runs currently at utwente.nl

**Comment by iisys-** [comment]
We found the issue. The update functionality sends the update request to http://localhost:16842/searsia/update/<resourceID>, which is hard-coded in engine.html (twice). I fixed this for now by hard-coding the correct URL. For our testing environment we'll circumvent this by adding any missing resources automatically.

**Comment by djoerd** [comment]
Woops, it is! Thanks for pointing this out! We'll change this in a future release...

**Comment by searsia** [comment]
This is no longer an issue in Version 1.x.x
